version: '3.4'

networks:
  scoutix-network:
    driver: bridge

services:
  mariadb-scoutix-service:
    image: mariadb:10.8
    container_name: mariadb-scoutix-container
    ports:
      - "4306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/dev/mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scoutix
      MYSQL_USER: scoutix_admin
      MYSQL_PASSWORD: scoutix
    networks:
      - scoutix-network

  pma-scoutix-service:
    image: phpmyadmin/phpmyadmin
    container_name: pma-scoutix-container
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: mariadb-scoutix-service
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PMADB: phpmyadmin
      MYSQL_ROOT_PASSWORD: root
    networks:
      - scoutix-network

  mailhog-scoutix-service:
    image: mailhog/mailhog
    container_name: mailhog-scoutix-container
    ports:
      - "1080:80"
    networks:
      - scoutix-network
