version: '3.4'

networks:
  scoutix-network:
    driver: bridge

services:
  nginx-scoutix-service:
    image: nginx:stable-alpine
    container_name: nginx-scoutix-container
    ports:
      - "80:80"
    volumes:
      - ./api/:/app
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: scoutix.co
      VIRTUAL_PORT: 3000
    depends_on:
      - php-scoutix-service
      - mariadb-scoutix-service
    networks:
      - scoutix-network

  node-scoutix-service:
    build:
      context: ./docker/dev/node
    container_name: node-scoutix-container
    entrypoint: [ "/bin/bash", "-c", "yarn install && yarn start" ]
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/app
    environment:
      VIRTUAL_HOST: scoutix.co
      VIRTUAL_PORT: 3000
    working_dir: /app
    networks:
      - scoutix-network

  php-scoutix-service:
    build:
      context: ./docker/dev/php
    container_name: php-scoutix-container
    ports:
      - "9000:9001"
    volumes:
      - ./api/:/app
    networks:
      - scoutix-network
