api_platform:
  defaults:
    pagination_enabled: false
  mapping:
    paths: [ '%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform/resources' ]
  formats:
    jsonld: [ 'application/ld+json' ]
    jsonhal: [ 'application/hal+json' ]
    jsonapi: [ 'application/vnd.api+json' ]
    json: [ 'application/json' ]
    xml: [ 'application/xml', 'text/xml' ]
    yaml: [ 'application/x-yaml' ]
    csv: [ 'text/csv' ]
    html: [ 'text/html' ]
    myformat: [ 'application/vnd.myformat' ]
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  swagger:
    api_keys:
      apiKey:
        name: Authorization
        type: header
    versions: [ 3 ]
  eager_loading:
    force_eager: false
