App\Entity\EventCategory:
  attributes:
    denormalization_context:
      groups: [ 'write' ]
    normalization_context:
      groups: [ 'read' ]
  collectionOperations:
    available:
      controller: App\Controller\Global\EventCategoroller::available
      method: GET
      path: /event_categories/available
    get: ~
    post: ~
