@startuml
package "BusinessRules" <<Node>> #FFF {
    package "Entity" <<Database>> #EEE {
        entity National {}
        entity Territory {} /'notion virtuel'/
        entity Locality {} /'groupe local'/
        entity Cluster {} /'groupe de groupes local'/

        entity User {} /'entité générique'/
        entity Member {}
        entity Scout {}
        entity Parent {}
        entity Branch {} /'branche des scouts'/
        entity Guide {} /'accompagnateur pédagogique'/
        entity Chef {}
        entity LocalityResponsible {}
        entity LocalityResponsibleDeputy {} /'adjoint'/
        entity TerritorialDelegate {} /'entité spécialisé de User et entité générique'/
        entity MissionManager {}
        entity Secretary {}
        entity Treasurer {}
        entity RPAF {} /'responsable financier territoire'/
        entity RPP {} /'responsable pôle pédagogique'/

        entity BoardOfDirectors {} /'conseil d'administration'/

        National "One" *--> "Many" Territory: own
        Territory "One" *--> "Many" Cluster: own
        Cluster "One" *--> "Many" Locality: own

        User <|-- Member
        User <|-- Parent
        User <|-- LocalityResponsible
        User <|-- LocalityResponsibleDeputy
        User <|-- TerritorialDelegate
        
        Member <|-- Scout
        Member <|-- Guide
        Member <|-- Chef

        TerritorialDelegate <|-- MissionManager
        TerritorialDelegate <|-- Secretary
        TerritorialDelegate <|-- Treasurer
        TerritorialDelegate <|-- RPAF
        TerritorialDelegate <|-- RPP

        Locality "One" *--> "Many" Member: is related to

        Parent "One" *--> "Many" Scout: is related to
        Scout "One" *--> "Many" Branch: have

        TerritorialDelegate "One" *--> "Many" Territory: connect
        LocalityResponsible "Many" -- "Many" Cluster: connect
        LocalityResponsibleDeputy "Many" -- "Many" Cluster: connect

        BoardOfDirectors "One" -- "Many" TerritorialDelegate: compound
    }
}
@enduml
